namespace RideStylerShowcase.strings {
    registerLanguage(LanguageKeys.En, {
        "vehicle-select-visualize-intro": "Visualize wheels, tires and suspension modifications on your vehicle.",
        "vehicle-select-share-intro":     "Share with your friends, or save for inspiration.",
        "select-your-vehicle":            "Select your Vehicle",
        "paint":                          "Paint",
        "suspension":                     "Suspension",
        "wheels":                         "Wheels",
        "tires":                          "Tires",
        "front":                          "Front",
        "rear":                           "Rear",
        "vehicle-details":                "Vehicle Details",
        "change-vehicle":                 "Change Vehicle",
        "wheel-details":                  "Wheel Details",
        "tire-details":                   "Tire Details",
        "select-paint":                   "Select Paint",
        "select-wheels":                  "Select Wheels",
        "select-tires":                   "Select Tires",
        "adjust-suspension":              "Adjust Suspension",
        "change-wheel-size":              "Change Wheel Size",
        "no-results":                     "No Results Found",
        "wheel-features-specs":           "Wheel Features & Specs",
        "share-my-vehicle":               "Share My Vehicle",
        "share-instructions":             "Scan the QR code or use the link to share or save your vehicle configuration.",
        "no-description-wheel":           "We don't have a description for this wheel yet",
        'show-specs':                     "Show Specs",
        'call':                           "Call",
        'size':                           "Size",
        'offset':                         "Offset",
        'bolt-pattern':                   "Bolt Pattern",
        'centerbore':                     "Centerbore",
        'price':                          "Price",
        'item-number':                    "Item #",
        'brands':                         "Brands",
        'finishes':                       "Finishes",
        'sizes':                          "Sizes",
        'all':                            "All",
        'all-brands':                     "All Brands",
        'all-finishes':                   "All Finishes",
        'all-sizes':                      "All Sizes",
        'filter-results':                 "Filter Results",
        'loading-ellipsis':               "Loading...",
        'show-count-format-tires':        "Show {count} Tires",
        'show-count-format-wheels':       "Show {count} Wheels",
        'specifications':                 "Specifications",
        'speed-rating':                   "Speed Rating",
        'any-speed-ratings':              "Any Speed Ratings",
        'features':                       "Features",
        'any-features':                   "Any Features",
        'finish':                         "Finish",
        'summary':                        "Summary"
    });
}